import { supabase } from '../config/supabase.js';
import { ApiError } from '../middleware/error.middleware.js';

/**
 * Creates a sale row for the completed order.
 * This is called automatically when an order's payment is confirmed.
 *
 * @param orderId UUID of the confirmed order
 */
export async function createSaleForOrder(orderId: string): Promise<void> {
  // 1. Fetch order details (buyer and total amount)
  const { data: order, error: orderError } = await supabase
    .from('orders')
    .select('buyer_id, total_amount')
    .eq('id', orderId)
    .single();

  if (orderError || !order) {
    throw new ApiError(404, `Order not found during sale creation: ${orderError?.message}`);
  }

  // 2. Insert into the sales table
  const { error: saleError } = await supabase
    .from('sales')
    .insert({
      order_id: orderId,
      distributor_id: order.buyer_id,
      amount: order.total_amount,
    });

  if (saleError) {
    // If it's a unique constraint violation (already confirmed / sale exists), throw a specific error
    if (saleError.code === '23505') {
      throw new ApiError(409, 'A sale has already been recorded for this order');
    }
    throw new ApiError(500, `Failed to record sale: ${saleError.message}`);
  }

  console.log(`✅ Recorded sale for order ${orderId} (amount: ${order.total_amount})`);

  // THEONUTRA V1: network bonuses are PV-based (Active Monthly + Differential)
  // and generated by the monthly compensation job — not as a % of order money.
}

/**
 * Get all commissions earned by a distributor, joined with sale details.
 * Used for the account/order-history-adjacent view.
 *
 * @param distributorId UUID of the distributor
 * @returns List of commissions with sale amount and date
 */
export async function getMyCommissions(distributorId: string) {
  const { data, error } = await supabase
    .from('commissions')
    .select(`
      id,
      level,
      amount,
      created_at,
      sales (
        id,
        amount,
        sale_date,
        order_id,
        distributor_id
      )
    `)
    .eq('beneficiary_id', distributorId)
    .order('created_at', { ascending: false });

  if (error) {
    throw new ApiError(500, `Failed to fetch commissions: ${error.message}`);
  }

  return data;
}

/**
 * Get total commission earned by a distributor in a given month.
 * Defaults to current month if not specified.
 *
 * @param distributorId UUID of the distributor
 * @param month Optional month string in YYYY-MM format
 * @returns Total commission amount for the month
 */
export async function getCommissionsSummary(distributorId: string, month?: string) {
  // Default to current month if not provided
  const targetMonth = month || new Date().toISOString().slice(0, 7); // YYYY-MM

  // Calculate start and end of the month in JavaScript
  const startDate = new Date(`${targetMonth}-01`);
  const endDate = new Date(startDate);
  endDate.setMonth(endDate.getMonth() + 1); // First day of next month

  const { data, error } = await supabase
    .from('commissions')
    .select('amount')
    .eq('beneficiary_id', distributorId)
    .gte('created_at', startDate.toISOString())
    .lt('created_at', endDate.toISOString());

  if (error) {
    throw new ApiError(500, `Failed to fetch commission summary: ${error.message}`);
  }

  const total = data.reduce((sum, commission) => sum + Number(commission.amount), 0);

  return {
    month: targetMonth,
    total_commission: total,
    commission_count: data.length,
  };
}
