import { supabase } from '../config/supabase.js';
import { ApiError } from '../middleware/error.middleware.js';
import * as loyaltyService from './loyalty.service.js';

/**
 * Creates a sale row for the completed order and awards loyalty points.
 * Called automatically when an order's payment is confirmed.
 *
 * Loyalty: 1 point per 1,000 of order currency amount (based on order value).
 *
 * THEONUTRA V1: network bonuses are PV-based (Active Monthly + Differential)
 * and generated by the monthly compensation job — not as a % of order money.
 */
export async function createSaleForOrder(orderId: string): Promise<void> {
  const { data: order, error: orderError } = await supabase
    .from('orders')
    .select('buyer_id, total_amount')
    .eq('id', orderId)
    .single();

  if (orderError || !order) {
    throw new ApiError(404, `Order not found during sale creation: ${orderError?.message}`);
  }

  const { error: saleError } = await supabase
    .from('sales')
    .insert({
      order_id: orderId,
      distributor_id: order.buyer_id,
      amount: order.total_amount,
    });

  if (saleError) {
    if (saleError.code === '23505') {
      throw new ApiError(409, 'A sale has already been recorded for this order');
    }
    throw new ApiError(500, `Failed to record sale: ${saleError.message}`);
  }

  console.log(`✅ Recorded sale for order ${orderId} (amount: ${order.total_amount})`);

  // Loyalty from wholesale order value (idempotent-ish: skip if already credited for this order)
  const orderAmount = Number(order.total_amount ?? 0);
  const loyaltyPoints = Math.floor(orderAmount / 1000);
  if (loyaltyPoints > 0) {
    const { data: existingLoyalty } = await supabase
      .from('loyalty_transactions')
      .select('id')
      .eq('profile_id', order.buyer_id)
      .eq('related_order_id', orderId)
      .maybeSingle();

    if (!existingLoyalty) {
      try {
        await loyaltyService.creditPoints(
          order.buyer_id,
          'wholesale_order',
          orderId,
          loyaltyPoints,
        );
        console.log(`✅ Credited ${loyaltyPoints} loyalty points for order ${orderId}`);
      } catch (loyaltyError) {
        console.error(`❌ Failed to credit loyalty for order ${orderId}:`, loyaltyError);
      }
    }
  }
}

/**
 * Get all commissions earned by a distributor, joined with sale details.
 */
export async function getMyCommissions(distributorId: string) {
  const { data, error } = await supabase
    .from('commissions')
    .select(`
      id,
      level,
      amount,
      created_at,
      sales (
        id,
        amount,
        sale_date,
        order_id,
        distributor_id
      )
    `)
    .eq('beneficiary_id', distributorId)
    .order('created_at', { ascending: false });

  if (error) {
    throw new ApiError(500, `Failed to fetch commissions: ${error.message}`);
  }

  return data;
}

/**
 * Get total commission earned by a distributor in a given month.
 */
export async function getCommissionsSummary(distributorId: string, month?: string) {
  const targetMonth = month || new Date().toISOString().slice(0, 7);

  const startDate = new Date(`${targetMonth}-01`);
  const endDate = new Date(startDate);
  endDate.setMonth(endDate.getMonth() + 1);

  const { data, error } = await supabase
    .from('commissions')
    .select('amount')
    .eq('beneficiary_id', distributorId)
    .gte('created_at', startDate.toISOString())
    .lt('created_at', endDate.toISOString());

  if (error) {
    throw new ApiError(500, `Failed to fetch commission summary: ${error.message}`);
  }

  const total = data.reduce((sum, commission) => sum + Number(commission.amount), 0);

  return {
    month: targetMonth,
    total_commission: total,
    commission_count: data.length,
  };
}
