export type ManageStackParamList = {
  ManageHome: undefined;
  DistributorList: undefined;
  DistributorDetail: { distributorId: string; distributorName: string };
  AddSeller: undefined;
  EditSeller: { distributorId: string };
  ResetPassword: { distributorId: string; distributorName: string };
  CountryList: undefined;
  AddCountry: undefined;
  EditCountry: { countryId: string };
  ProductList: undefined;
  AddEditProduct: { productId?: string };
  PostNews: undefined;
  ManageNews: undefined;
  EditNews: { newsId: string };
  AddArticle: undefined;
  ManageArticles: undefined;
  EditArticle: { articleId: string };
  PendingPayments: undefined;
  ManageWithdrawals: undefined;
  ManageTraining: undefined;
  ManageTrainingMaterials: { categoryId: string; categoryName: string };
  ManageEvents: undefined;
  AddEditEvent: { eventId?: string };
  ManageKyc: undefined;
  CompanyAnalytics: undefined;
  ManageOPB: undefined;
  ManageCommissions: undefined;
  SystemJobs: undefined;
};